services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: melokafe_mssql
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "MeloKafe_2025_Sql!"
    ports:
      - "1433:1433"

  api:
    build: .
    container_name: melokafe_api
    ports:
      - "5000:8080"
    depends_on:
      - db 
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Database=MeloKafeDb;User Id=sa;Password=MeloKafe_2025_Sql!;TrustServerCertificate=True;"